### ISSUE TITLE
Update the .csproj to match the latest nuget package

### ISSUE THREAD

**Issue by addd45** [net-daemon/netdaemon-app-template#3]
Would just be nice if this repository would get updated each time the main project gets updated :).

the .csproj still points to .21-alpha or something. In theory, each update to netdaemon should also update this project.

**Comment by helto4real** [comment]
You are right my friend... Will do

**Comment by helto4real** [comment]
Updated to latest 0.3.1-alpha, thanks @addd45 for reminder
