### ISSUE TITLE
Test Project not working

### ISSUE THREAD

**Issue by andersmoldin** [net-daemon/netdaemon-app-template#35]
After cloning the template-project, following the guide on https://netdaemon.xyz/docs/started/development, I get the following to errors after building.

![image](https://user-images.githubusercontent.com/1079107/144004143-d5d2dc4f-cc38-4668-a0da-370a94e27fc7.png)

CS0246	The type or namespace name 'HelloWorld' could not be found (are you missing a using directive or an assembly reference?)

CS0246	The type or namespace name 'HelloWorldApp' could not be found (are you missing a using directive or an assembly reference?)

**Comment by srdjansimic** [comment]
I did not understand why there is not parameters in line 24, but since I am just starting with NetDaemon, just comment it, and also line 2. HelloWorld app is in HassModel namespace. This isn't the whole solution but it will jump start you if you want to see how this whole platform works.

**Comment by helto4real** [comment]
Thanks for reporting. We recently updated to a new model. I think we forgot to test the test project. I will look into it. Thanks for reporting.

**Comment by helto4real** [comment]
Thank you. I fixed the example now to work. We currently only have a test story for old V2 API. We are working on providing a mock class that can be used for HassModel based apps too. Enjoy.

**Comment by helto4real** [comment]
Closing now
