### ISSUE TITLE
Don't use persistent notification as an example app

### ISSUE THREAD

**Issue by danrspencer** [net-daemon/netdaemon-app-template#39]
So I've just been setting up NetDaemon (nice work by the way, this looks awesome). Got things all installed and the template moved over then went on with the rest of my day. Came back in the evening to find I've got over 2000 persistent notifications in Home Assistant I need to figure out how to clear down. They're almost crashing the notification window as it's clearly not designed for that many notifications.

I think another example less likely to cause problems if not removed before starting NetDaemon may be more suitable.

**Comment by helto4real** [comment]
Ouch. Sorry I missed this issue.. Yea that is a good idea. I will look into it.
