### ISSUE TITLE
[Focus] attribute is being honoured in production for .csproj deployments

### ISSUE THREAD

**Issue by skotl** [net-daemon/netdaemon-app-template#41]
The original issue is as per title, that a .csproj deployment incorrectly honours the `[Focus]` attribute, which should only happen in development environments.

The root cause chain seems to be:

1. `ASPNETCORE_ENVIRONMENT` is set to `Development` when the project is built and executed inside HA
2. Commit #33 sets `ASPNETCORE_ENVIRONMENT` in the `launchSettings.json` file

**Comment by skotl** [comment]
Right now I suspect that we are misusing `Properties/launchSettings.json` as it's not supposed to be deployed to production, so I see one of two ways forward:

1. Remove `Properties/launchSetting.json` from git
_or..._
2. Change the file to have a `Debug` and a `Release` profile and update the configurations to refer to each (so we would have a `daemonapp: Debug` and a `daemonApp: Release` configuration)

Option two adds some more complexity, and we'd need to ensure that ND is building the correct profile, so option one _seems_ the better route but I'm unsure whether this might break anyone else's workflow.

**Comment by skotl** [comment]
...actually... for the original issue, it's only important to remove properties/launchsettings.json - the dev env folders would be good practice but aren't needed to address the reported issue

**Comment by helto4real** [comment]
Thank you for giving your time on this. Yea this is a interesting problem. I wanted things to be "working out of the box" for people downloading the template. The template is first and most a helper to build, debug and deploy the apps. What we could do is force the environment var default in the docker image to be production for add-on. What you think @FrankBakkerNl ?

**Comment by skotl** [comment]
As discussed, closing this as resolved by updated documentation (PR #90 on netdaemon-docs).

Appreciate the support as ever!
