### ISSUE TITLE
Nymea Mqtt Bridge

### ISSUE THREAD

**Issue by grisia** [net-daemon/netdaemon-app-template#72]
I've tried to create a bridge between my Nymea gateway and home assistants.
Currently I only operate my entrance gate via the gateway. Therefore only the gate is supported in the implementation. Communication with the Nymea Gateway is implemented via an encrypted TCP socket.

Furthermore, the component must be initialized in the constructor of the `NymeaMqttBridge` class.
`_marantecControlX52 = new MarantecControlX52`(...)`

In Home Assistant, the services:
* `lowbit_nymea_mqtt_bridge_start_push_button_authentication`
* `lowbit_nymea_mqtt_bridge_get_things`
* `lowbit_nymea_mqtt_bridge_introspect_api`
* `lowbit_nymea_mqtt_bridge_get_thing_classes`

are provided.

Maybe someone can use it, if not please just delete it. Unfortunately, ZIP archives cannot be uploaded to the HA forum. That's why I'm providing it here.
The solution works for me so far... ;)

[nymea_mqtt_bridge.zip](https://github.com/net-daemon/netdaemon-app-template/files/9890953/nymea_mqtt_bridge.zip)

The first patch is required because not all required libraries are referenced in the standard.
The second is optional.

* [Referencing TRUSTED_PLATFORM_ASSEMBLIES #771](https://github.com/net-daemon/netdaemon/issues/771)
* [JsonIgnoreCondition.WhenWritingNull to EntityCreationPayloadHelper #772](https://github.com/net-daemon/netdaemon/issues/772)

I think in general this implementation belongs directly to home assistant... But so far nobody seems to have found it for... The only thing I found was this forum entry  [Nymea/Maveo integration](https://community.home-assistant.io/t/nymea-maveo-integration/144389)

**Comment by helto4real** [comment]
Thank you for your contribution. It is not a safe thing to provide files directly in Issues. This is a security problem so I remove any issue providing zip files. This medium is not for storage. I will close this issue.
